# General Settings
name: Jack Riminton
job_title: MBA student VC
email: jriminton@gmail.com
description: I'm a techy MBA who used to be in the army. Check out my art and coding projects above, my blog over there --> or my social media below
avatar: https://pbs.twimg.com/profile_images/907272099869454337/k7mheVeU_400x400.jpg
favicon: /favicon.ico
twitter_handler: jackrim1
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: 'https://www.facebook.com/jack.rim' }
-  { name: twitter, url: 'http://twitter.com/jackrim1' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/jack-riminton-68bb9a90/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/jackrim1' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: etsy, url: 'https://www.etsy.com/uk/shop/MatisseAndCo'}

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed